# Generated by Django 5.2.5 on 2026-04-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='sector',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
