# Generated by Django 5.2.5 on 2026-06-04 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=200)),
                ('scientific_name', models.CharField(max_length=200, unique=True)),
                ('family', models.CharField(max_length=200)),
                ('tree_type', models.CharField(choices=[('deciduous', 'Deciduous'), ('evergreen', 'Evergreen'), ('conifer', 'Conifer')], max_length=50)),
                ('native_region', models.CharField(max_length=255)),
                ('conservation_status', models.CharField(choices=[('LC', 'Least Concern'), ('NT', 'Near Threatened'), ('VU', 'Vulnerable'), ('EN', 'Endangered'), ('CR', 'Critically Endangered')], default='LC', max_length=2)),
            ],
            options={
                'ordering': ['common_name'],
            },
        ),
        migrations.CreateModel(
            name='Threat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('threat_type', models.CharField(choices=[('disease', 'Disease'), ('pest', 'Pest'), ('environmental', 'Environmental')], max_length=20)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threats', to='trees.tree')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_height_m', models.FloatField(blank=True, null=True)),
                ('canopy_spread_m', models.FloatField(blank=True, null=True)),
                ('trunk_diameter_cm', models.FloatField(blank=True, null=True)),
                ('growth_rate', models.CharField(blank=True, choices=[('slow', 'Slow'), ('moderate', 'Moderate'), ('fast', 'Fast')], max_length=20)),
                ('lifespan_years', models.PositiveIntegerField(blank=True, null=True)),
                ('leaf_description', models.TextField(blank=True)),
                ('bark_description', models.TextField(blank=True)),
                ('flower_description', models.TextField(blank=True)),
                ('fruit_description', models.TextField(blank=True)),
                ('tree', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='physical', to='trees.tree')),
            ],
        ),
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('native_range', models.TextField(blank=True)),
                ('introduced_regions', models.TextField(blank=True)),
                ('preferred_climate', models.CharField(blank=True, max_length=200)),
                ('hardiness_zone', models.CharField(blank=True, max_length=100)),
                ('elevation_min_m', models.IntegerField(blank=True, null=True)),
                ('elevation_max_m', models.IntegerField(blank=True, null=True)),
                ('tree', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='habitat', to='trees.tree')),
            ],
        ),
        migrations.CreateModel(
            name='GrowingConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunlight', models.CharField(blank=True, max_length=100)),
                ('soil_type', models.CharField(blank=True, max_length=200)),
                ('soil_ph', models.CharField(blank=True, max_length=100)),
                ('water_requirements', models.CharField(blank=True, max_length=100)),
                ('drought_tolerance', models.CharField(blank=True, max_length=100)),
                ('frost_tolerance', models.CharField(blank=True, max_length=100)),
                ('tree', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='growing_conditions', to='trees.tree')),
            ],
        ),
        migrations.CreateModel(
            name='EcologicalImportance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carbon_sequestration', models.TextField(blank=True)),
                ('wildlife_supported', models.TextField(blank=True)),
                ('pollinators_attracted', models.TextField(blank=True)),
                ('soil_benefits', models.TextField(blank=True)),
                ('ecosystem_role', models.TextField(blank=True)),
                ('tree', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ecology', to='trees.tree')),
            ],
        ),
        migrations.CreateModel(
            name='CareGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pruning_requirements', models.TextField(blank=True)),
                ('fertilization', models.TextField(blank=True)),
                ('watering_schedule', models.TextField(blank=True)),
                ('planting_time', models.TextField(blank=True)),
                ('tree', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='care', to='trees.tree')),
            ],
        ),
        migrations.CreateModel(
            name='TreeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trees/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('image_type', models.CharField(choices=[('general', 'General'), ('leaf', 'Leaf'), ('bark', 'Bark'), ('flower', 'Flower'), ('fruit', 'Fruit')], default='general', max_length=20)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='trees.tree')),
            ],
        ),
        migrations.CreateModel(
            name='TreeUses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timber', models.TextField(blank=True)),
                ('landscaping', models.TextField(blank=True)),
                ('medicinal', models.TextField(blank=True)),
                ('cultural', models.TextField(blank=True)),
                ('food', models.TextField(blank=True)),
                ('tree', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='trees.tree')),
            ],
        ),
    ]
