# Generated by Django 5.2.5 on 2026-06-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='scientific_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
