# Generated by Django 5.2.5 on 2026-06-19 12:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0002_alter_tree_scientific_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tree',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
