# Generated by Django 5.2.5 on 2026-06-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupschedule',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
